---
Name: goldfinch-helpers
---

SilverStripe\ORM\DataObject:
  extensions:
    - Goldfinch\Helpers\Extensions\DataObjectExtension

SilverStripe\Core\Injector\Injector:
  ShortcodeVarchar:
    class: Goldfinch\Helpers\ORM\FieldType\DBVarcharShortcode

SilverStripe\ORM\FieldType\DBHTMLText:
  extensions:
    - Goldfinch\Helpers\Extensions\DBHighlight

SilverStripe\ORM\FieldType\DBString:
  extensions:
    - Goldfinch\Helpers\Extensions\DBHighlight

SilverStripe\ORM\FieldType\DBHTMLVarchar:
  extensions:
    - Goldfinch\Helpers\Extensions\DBHighlight

SilverStripe\Admin\ModelAdmin:
  extensions:
    - Goldfinch\Helpers\Extensions\AdminPaginator
    - Goldfinch\Helpers\Extensions\AdminPlain
    - Goldfinch\Helpers\Extensions\AdminSortable

SilverStripe\Admin\SecurityAdmin:
  extensions:
    - Goldfinch\Helpers\Extensions\SecurityAdminExtension

SilverStripe\Security\DefaultAdminService:
  extensions:
    - Goldfinch\Helpers\Extensions\DefaultAdminServiceExtension
