---
Name: goldfinch-helpers
---
SilverStripe\ORM\DataObject:
  extensions:
    - Goldfinch\Helpers\Extensions\DataObjectExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\ORM\DataList:
    class: Goldfinch\Helpers\ORM\DataList
  ShortcodeVarchar:
    class: Goldfinch\Helpers\ORM\FieldType\DBVarcharShortcode

SilverStripe\ORM\FieldType\DBHTMLText:
  extensions:
    - Goldfinch\Helpers\Extensions\DBHighlightExtension

SilverStripe\ORM\FieldType\DBString:
  extensions:
    - Goldfinch\Helpers\Extensions\DBHighlightExtension

SilverStripe\ORM\FieldType\DBHTMLVarchar:
  extensions:
    - Goldfinch\Helpers\Extensions\DBHighlightExtension

SilverStripe\Admin\ModelAdmin:
  extensions:
    - Goldfinch\Helpers\Extensions\AdminPaginator
    - Goldfinch\Helpers\Extensions\AdminPlain
    - Goldfinch\Helpers\Extensions\AdminSortable

SilverStripe\Admin\SecurityAdmin:
  extensions:
    - Goldfinch\Helpers\Extensions\SecurityAdminExtension

SilverStripe\Security\DefaultAdminService:
  extensions:
    - Goldfinch\Helpers\Extensions\DefaultAdminServiceExtension
