---
Name: goldfinch-helpers
---

SilverStripe\ORM\DataObject:
  extensions:
    - Goldfinch\Helpers\Extensions\DataObjectExtension

SilverStripe\Core\Injector\Injector:
  SCVarchar:
    class: Goldfinch\Helpers\ORM\FieldType\DBVarcharShortcode
